name: Build Framework

on:
  workflow_dispatch:
    inputs:
      grdb_tag:
        description: "GRDB Tag (e.g. v7.0.0)"
        required: true
        type: string
      tag:
        description: "Release Tag (e.g. v1.2.3)"
        required: true
        type: string

concurrency:
  group: build
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  build-notarize:
    timeout-minutes: 30
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Select .xcode-version
        run: sudo xcodes select

      - name: Install mint
        run: brew install mint

      - name: mint bootstrap
        run: mint bootstrap

      - name: ./prepare_release.sh
        run: |
          ./prepare_release.sh ${{ github.event.inputs.grdb_tag }} ${{ github.event.inputs.tag }}
