name: Build Framework

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag to build (e.g. v1.2.3)"
        required: true
        type: string

concurrency:
  group: build
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  build-notarize:
    timeout-minutes: 30
    runs-on: sequoia-xcode
    steps:
      - name: Read CIRRUS_HTTP_CACHE_HOST from 1password
        id: op-action-cache-url-secret
        uses: 1password/load-secrets-action@v2
        with:
          export-env: false
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.NOT_STARTING_WITH_GITHUB_SERIESOS_GRDB_SWIFT_1PASSWORD_SERVICE_ACCOUNT }}
          CIRRUS_HTTP_CACHE_HOST: "op://Series Production/github-actions-cache-server/host"

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Select .xcode-version
        run: sudo xcodes select

      - name: Cache mint
        uses: cirruslabs/cache@v4
        env:
          CIRRUS_HTTP_CACHE_HOST: ${{ steps.op-action-cache-url-secret.outputs.CIRRUS_HTTP_CACHE_HOST }}
        with:
          path: ~/.mint
          key: $-mint-macos-$

      - name: Install mint
        run: brew install mint

      - name: mint bootstrap
        run: mint bootstrap

      - name: ./prepare_release.sh
        run: |
          ./prepare_release.sh ${{ github.event.inputs.tag }}
